### PR TITLE
Additional docker config information

### PR DESCRIPTION
**Pull request by Conky5**

### CODE REVIEW

**Review by mgreau — APPROVED** [review]
LGTM 
Great improvement with the config.json file 👍

**Comment by Conky5** [comment]
Thanks! I just realized I made a mistake with the script changes, I'll have to put a suggestion on the main PR I think.

**Comment by mgreau** [comment]
I sent you an invite to be a collaborator for this repo

**Comment by mgreau** [comment]
Also I would like to add a gif to show we can follow the in-progress logs. That will help for asking to update the PR about  « after the fact » https://github.com/knative/build-pipeline/pull/430/files

**Pull request merged**
